<?php $cart  = $this->getQuoteData(); ?>
<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('css/pdfcart/pdfcart.css') ?>" media="all">
	<link href="<?php echo $this->getSkinUrl('favicon.ico') ?>" rel="icon" type="image/ico" >
	<title><?php echo Mage::getStoreConfig('pdfcart/general/page_title', Mage::app()->getStore()->getStoreId())?></title>
</head>
<body>
<table>
	<tr>
		<td><img src="<?php echo $this->getSkinUrl('images/logo.png')?>"></td>
	</tr>
</table>
	<table>
		<tr>
			<td>Data: <?php echo Mage::getModel('core/date')->date('d/m/Y H:i:s') ?></td>
		</tr>
		<tr>
			<td>Produto</td>
			<td>Quantidade</td>
			<td>Preço Un.</td>
			<td>Subtotal</td>
		</tr>
			<?php foreach ($cart as $item) { ?>
				<tr>
					<td><?= $item->name; ?></td>
					<td><?= Mage::helper('core')->currency($item->price, true, false); ?></td>
					<td><?= $item->qty ?></td>
					<td><?= Mage::helper('core')->currency($item->subtotal, true, false); ?></td>
				</tr>
			<?php } ?>
		<tr>
			<td colspan=2>&nbsp;</td>
			<td>Total</td>
			<td><?= Mage::helper('core')->currency($this->getQuoteTotal(), true, false);?></td>
		</tr>
	</table>
	<table>
		<tr>
			<td rowspan=4>Obs: Os valores e disponibilidade de produtos podem sofrer alteração a qualquer momento.</td>
		</tr>
	</table>
</body>
</html>
<table>
